name: congitiveai
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.11
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.4
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  flutter_sound: ^9.16.3
  path_provider: ^2.1.4
  speech_to_text: ^7.0.0
  image_picker: ^0.8.4+11
  flutter_tts: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Enables Material Icons
  uses-material-design: true

  # Asset files
  assets:
    - assets/robo.jpg

  # Uncomment below to add more assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Custom font example (uncomment and edit if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
